name: deploy-book

# Define when this workflow should run
on:
  push:
    branches:
      - main    # Triggers on pushes to the main branch
    paths:
      - 'docs/**'    # Optional: Only trigger if changes are made to the docs folder
  pull_request:
    branches:
      - main    # Triggers on pull requests to the main branch

# Define the jobs to be executed
jobs:
  deploy-book:
    runs-on: ubuntu-latest    # Specifies the runner environment

    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -U jupyter-book

      # Build the book
      - name: Build the book
        run: |
          jupyter-book build docs

      # Copy images to gh-pages branch
      - name: Copy images to gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          cp -R markdown/images/* _images/
          git add _images/
          git commit -m "Copy images for GitHub Pages"
          git push origin gh-pages

      # Push the book's HTML to GitHub Pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
